-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20/01/2015 1:24:35
-- Server version: 5.5.8
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE db_asistencia;

--
-- Definition for table tbl_area
--
DROP TABLE IF EXISTS tbl_area;
CREATE TABLE IF NOT EXISTS tbl_area (
  idArea INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  PRIMARY KEY (idArea)
)
ENGINE = INNODB
AUTO_INCREMENT = 9
AVG_ROW_LENGTH = 2340
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_instituto
--
DROP TABLE IF EXISTS tbl_instituto;
CREATE TABLE IF NOT EXISTS tbl_instituto (
  idInstituto INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  PRIMARY KEY (idInstituto)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 5461
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_user
--
DROP TABLE IF EXISTS tbl_user;
CREATE TABLE IF NOT EXISTS tbl_user (
  id_user INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (id_user)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_practicante
--
DROP TABLE IF EXISTS tbl_practicante;
CREATE TABLE IF NOT EXISTS tbl_practicante (
  idPracticante INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  apellido VARCHAR(100) NOT NULL,
  fechaInicio DATE NOT NULL,
  fechaFinal DATE NOT NULL,
  idArea INT(11) NOT NULL,
  idInstituto INT(11) NOT NULL,
  PRIMARY KEY (idPracticante),
  UNIQUE INDEX UK_tbl_practicante_idPracticante (idPracticante),
  CONSTRAINT FK_tbl_practicante_tbl_area_idArea FOREIGN KEY (idArea)
    REFERENCES tbl_area(idArea) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_tbl_practicante_tbl_instituto_idInstituto FOREIGN KEY (idInstituto)
    REFERENCES tbl_instituto(idInstituto) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_asistencia
--
DROP TABLE IF EXISTS tbl_asistencia;
CREATE TABLE IF NOT EXISTS tbl_asistencia (
  idAsistencia INT(11) NOT NULL AUTO_INCREMENT,
  idPracticante INT(11) NOT NULL,
  asistio SMALLINT(6) NOT NULL,
  fecha DATE NOT NULL,
  PRIMARY KEY (idAsistencia),
  CONSTRAINT FK_tbl_asistencia_tbl_practicante_idPracticante FOREIGN KEY (idPracticante)
    REFERENCES tbl_practicante(idPracticante) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 34
AVG_ROW_LENGTH = 3276
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

DELIMITER $$

--
-- Definition for procedure prc_cnd_asist_practicantes
--
DROP PROCEDURE IF EXISTS prc_cnd_asist_practicantes$$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE prc_cnd_asist_practicantes(IN fecha DATE)
BEGIN
  DROP TABLE IF EXISTS tabla1;
DROP TABLE IF EXISTS tabla2;
  create temporary table tabla1
  SELECT a.idAsistencia, a.idPracticante, b.nombre,b.apellido, a.fecha, a.asistio FROM tbl_asistencia a
  INNER JOIN tbl_practicante b ON a.idPracticante = b.idPracticante
  WHERE a.fecha = fecha;
 
  create temporary table tabla2
  SELECT b.idAsistencia, a.idPracticante,a.nombre,a.apellido,a.fechaInicio, a.fechaFinal, b.fecha,b.asistio, a.idArea,a.idInstituto FROM tbl_practicante a LEFT JOIN
  tabla1 b ON a.idPracticante = b.idPracticante;

SELECT a.idAsistencia, a.idPracticante, a.nombre, a.apellido, a.fechaInicio,a.fechaFinal, b.nombre AS area, c.nombre AS instituto, a.fecha, a.asistio  FROM tabla2 a INNER JOIN tbl_area b ON a.idArea = b.idArea
  INNER JOIN tbl_instituto c ON a.idInstituto = c.idInstituto;
END
$$

DELIMITER ;

-- 
-- Dumping data for table tbl_area
--
INSERT INTO tbl_area VALUES
(1, 'DPTO. NUTRICION'),
(2, 'CS. HUAURA -PSICOLOGIA'),
(3, 'UNIDAD ESTADISTICA E INFORMATICA'),
(4, 'SERVICIOS GENERALES'),
(5, 'UNIDAD DE ECONOMIA'),
(7, 'DPTO. ODONTOLOGIA'),
(8, 'APOYO ADMINISTRATIVO MR. HUALMAY');

-- 
-- Dumping data for table tbl_instituto
--
INSERT INTO tbl_instituto VALUES
(1, 'UNJFSC'),
(2, 'UAP'),
(3, 'SENATI');

-- 
-- Dumping data for table tbl_user
--
INSERT INTO tbl_user VALUES
(1, 'admin', '123');

-- 
-- Dumping data for table tbl_practicante
--
INSERT INTO tbl_practicante VALUES
(1, 'JANIA KATHERINE', 'PARIA VELASQUEZ', '2014-01-01', '2014-03-31', 1, 1),
(2, 'LISETTE GISELA', 'RAVENA NICHO', '2014-01-01', '2014-03-31', 1, 1);

-- 
-- Dumping data for table tbl_asistencia
--
INSERT INTO tbl_asistencia VALUES
(1, 1, 1, '2015-01-11'),
(2, 1, 0, '2015-01-10'),
(4, 1, 0, '2015-01-08'),
(5, 2, 0, '0000-00-00'),
(33, 1, 0, '2015-01-20');

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;