-- Script was generated by Devart dbForge Studio for MySQL, Version 4.50.285.0
-- Script date 31/12/2014 12:47:31
-- Server version: 5.5.8
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Definition for database db_asistencia
--
DROP DATABASE IF EXISTS db_asistencia;
CREATE DATABASE IF NOT EXISTS db_asistencia
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

-- 
-- Set default database
--
USE db_asistencia;

--
-- Definition for table tbl_area
--
CREATE TABLE IF NOT EXISTS tbl_area (
  idArea INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  PRIMARY KEY (idArea)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_instituto
--
CREATE TABLE IF NOT EXISTS tbl_instituto (
  idInstituto INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  PRIMARY KEY (idInstituto)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_user
--
CREATE TABLE IF NOT EXISTS tbl_user (
  id_user INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (id_user)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_practicante
--
CREATE TABLE IF NOT EXISTS tbl_practicante (
  idPracticante INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  apellido VARCHAR(100) NOT NULL,
  fechaInicio DATE NOT NULL,
  fechaFin DATE NOT NULL,
  idArea INT(11) NOT NULL,
  idInstituto INT(11) NOT NULL,
  PRIMARY KEY (idPracticante),
  INDEX FK_tbl_practicante_tbl_instituto_idInstituto (idInstituto),
  UNIQUE INDEX idArea (idArea),
  CONSTRAINT FK_tbl_practicante_tbl_area_idArea FOREIGN KEY (idArea)
    REFERENCES tbl_area(idArea),
  CONSTRAINT FK_tbl_practicante_tbl_instituto_idInstituto FOREIGN KEY (idInstituto)
    REFERENCES tbl_instituto(idInstituto)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_asistencia
--
CREATE TABLE IF NOT EXISTS tbl_asistencia (
  idAsistencia INT(11) NOT NULL AUTO_INCREMENT,
  idPracticante INT(11) NOT NULL,
  asistio SMALLINT(6) NOT NULL,
  PRIMARY KEY (idAsistencia),
  INDEX FK_tbl_asistencia_tbl_practicante_idPracticante (idPracticante),
  CONSTRAINT FK_tbl_asistencia_tbl_practicante_idPracticante FOREIGN KEY (idPracticante)
    REFERENCES tbl_practicante(idPracticante)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table tbl_area
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_instituto
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_user
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_practicante
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_asistencia
--
-- Table does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;